---
# 환경 설정
---

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [2]:
!pip install mxnet
!pip install gluonnlp tqdm
!pip install sentencepiece
!pip install transformers==3.0.2
!pip install torch

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
  Using cached transformers-3.0.2-py3-none-any.whl (769 kB)
  Using cached tokenizers-0.8.1rc1-cp37-cp37m-manylinux1_x86_64.whl (3.0 MB)
  Attempting uninstall: tokenizers
    Found existing installation: tokenizers 0.10.3
    Uninstalling tokenizers-0.10.3:
      Successfully uninstalled tokenizers-0.10.3
  Attempting uninstall: transformers
    Found existing installation: transformers 4.8.1
    Uninstalling transformers-4.8.1:
      Successfully uninstalled transformers-4.8.1
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [3]:
# !git clone https://github.com/SKTBrain/KoBERT.git

In [4]:
cd /content/drive/MyDrive/aiffel/NLP/KoBERT

/content/drive/MyDrive/aiffel/NLP/KoBERT


In [5]:
!pip install -r requirements.txt

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
  Using cached transformers-4.8.1-py3-none-any.whl (2.5 MB)
  Using cached tokenizers-0.10.3-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (3.3 MB)
  Attempting uninstall: tokenizers
    Found existing installation: tokenizers 0.8.1rc1
    Uninstalling tokenizers-0.8.1rc1:
      Successfully uninstalled tokenizers-0.8.1rc1
  Attempting uninstall: transformers
    Found existing installation: transformers 3.0.2
    Uninstalling transformers-3.0.2:
      Successfully uninstalled transformers-3.0.2


In [6]:
pip install wandb

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [7]:
pip install transformers-interpret

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [8]:
import wandb

wandb.login()
wandb.init()

ERROR:wandb.jupyter:Failed to detect the name of this notebook, you can set it manually with the WANDB_NOTEBOOK_NAME environment variable to enable code saving.
wandb: Currently logged in as: glad415. Use `wandb login --relogin` to force relogin


In [9]:
import torch
from torch import nn
import torch.nn.functional as F
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
import gluonnlp as nlp
import numpy as np
from tqdm import tqdm, tqdm_notebook

In [10]:
import pandas as pd 
from sklearn.model_selection import train_test_split
import re
import matplotlib.pyplot as plt
from sklearn.metrics import f1_score

In [11]:
#kobert
from kobert.utils import get_tokenizer
from kobert.pytorch_kobert import get_pytorch_kobert_model

#transformers
from transformers import AdamW
from transformers.optimization import get_cosine_schedule_with_warmup

In [12]:
# GPU 사용
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

In [13]:
from transformers import AutoTokenizer, AutoModel

tokenizer = AutoTokenizer.from_pretrained("/content/drive/MyDrive/aiffel/AIFFELTON/TAPT_Model_Save")

bertmodel = AutoModel.from_pretrained("/content/drive/MyDrive/aiffel/AIFFELTON/TAPT_Model_Save", num_labels = 5)

Some weights of the model checkpoint at /content/drive/MyDrive/aiffel/AIFFELTON/TAPT_Model_Save were not used when initializing BertModel: ['cls.predictions.transform.LayerNorm.bias', 'cls.predictions.transform.dense.weight', 'cls.predictions.decoder.bias', 'cls.predictions.bias', 'cls.predictions.decoder.weight', 'cls.predictions.transform.dense.bias', 'cls.predictions.transform.LayerNorm.weight']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of BertModel were not initialized from the model checkpoint at /content/drive/MyDrive/aiffel/AIFFELTON/TAPT_Model_Save and are newly

---
# 학습용 데이터셋 전처리
---

In [14]:
train_data = pd.read_csv('/content/drive/MyDrive/aiffel/AIFFELTON/for_model_labeling_folder/only_train.csv')
train_data = train_data[train_data['dataset'] == 'crawlling']

In [15]:
train_data.columns = ['review','dataset','taste','delivery','quantity']
train_data = train_data[['review','dataset','taste','quantity','delivery']]
train_data = train_data.reset_index(drop = True)
train_data

review    dataset  taste  \
0      현생인류가 감당하기에는 110만 년은 이른 기술력이다 이것이 정교함 이것이 집중력 ...  crawlling      0   
1                                         소스도 듬뿍 맛도 있었어요  crawlling      1   
2                                        맛있어요 돈까스덮밥이 좋네요  crawlling      1   
3                                맛있게 잘먹었어요 근데 쫄면사이즈업이맞나요  crawlling      1   
4                                           딱보통이었음 치킨이아쉽  crawlling      0   
...                                                  ...        ...    ...   
31204                                        맛잇게 잘먹엇어용 ㅎ  crawlling      1   
31205  호식이 두마리 치킨은 개인적으로 매운 간장치킨이 젤 맛있는거 같아요 앞으로도 쭉 시...  crawlling      1   
31206                                         오늘도 잘먹었습니당  crawlling      0   
31207                                       빅맥은 역시 사랑이네요  crawlling      0   
31208                  너무배고파서먹느라 사진은어니언링4개남은거 버거킹은항상맛있어요  crawlling      1   

       quantity  delivery  
0             0         0  
1             0         0  
2             0         0  
3             0         0  
4             0         0  
...         ...       ...  
31204         0         0  
31205         0         0  
31206         0         0  
31207         0         0  
31208         0         0  

[31209 rows x 5 columns]

In [16]:
test_data = pd.read_csv('/content/drive/MyDrive/aiffel/AIFFELTON/for_model_labeling_folder/only_bench.csv')
test_data

review  taste_label  \
0                                     15분만에 왔네요 배달도 빠르고            0   
1                              1955더블 맛있네요 배달이 좀 오래걸렸어요            1   
2                1시간 넘게 기다렸고 그래서 식어서 왔지만 그래도 맛있었으니 됐습니다            1   
3                         1시간지남 아직 안옴 그런데 후기작성하라고 메세지 옴            0   
4                                 1인분으로 딱적당해요 많지도 적지도않은            0   
...                                                 ...          ...   
4638                                         흐으 참 맛있습니다            1   
4639                              흔들리지 않게 잘 고정돼서 와서 좋았구            0   
4640  흠 개인의취향 다른메뉴는 좋은데 이메뉴는 너무 퍽퍽한 맛을 낸다는 제 개인적인 입맛...            1   
4641                                  흠 빅맥보단 치킨버거가 괜찬은듯            0   
4642        ㅠㅠ 사진찍을 사이도없이 다먹고알았네요 너무맛나요 특히 머스타드소스가 신의한수            1   

      deliver_label  quantity_label  
0                 1               0  
1                 1               0  
2                 1               0  
3                 1               0  
4                 0               1  
...             ...             ...  
4638              0               0  
4639              1               0  
4640              0               0  
4641              0               0  
4642              0               0  

[4643 rows x 4 columns]

In [17]:
test_data.columns = ['review','taste','delivery','quantity']
test_data = test_data[['review','taste','quantity','delivery']]
# train_data = train_data.reset_index(drop = True)
test_data

review  taste  quantity  \
0                                     15분만에 왔네요 배달도 빠르고      0         0   
1                              1955더블 맛있네요 배달이 좀 오래걸렸어요      1         0   
2                1시간 넘게 기다렸고 그래서 식어서 왔지만 그래도 맛있었으니 됐습니다      1         0   
3                         1시간지남 아직 안옴 그런데 후기작성하라고 메세지 옴      0         0   
4                                 1인분으로 딱적당해요 많지도 적지도않은      0         1   
...                                                 ...    ...       ...   
4638                                         흐으 참 맛있습니다      1         0   
4639                              흔들리지 않게 잘 고정돼서 와서 좋았구      0         0   
4640  흠 개인의취향 다른메뉴는 좋은데 이메뉴는 너무 퍽퍽한 맛을 낸다는 제 개인적인 입맛...      1         0   
4641                                  흠 빅맥보단 치킨버거가 괜찬은듯      0         0   
4642        ㅠㅠ 사진찍을 사이도없이 다먹고알았네요 너무맛나요 특히 머스타드소스가 신의한수      1         0   

      delivery  
0            1  
1            1  
2            1  
3            1  
4            0  
...        ...  
4638         0  
4639         1  
4640         0  
4641         0  
4642         0  

[4643 rows x 4 columns]

In [18]:
import numpy as np 

total_data_text = list(train_data['review'])
# 텍스트데이터 문장길이의 리스트를 생성한 후
num_tokens = [len(tokens) for tokens in total_data_text]
num_tokens = np.array(num_tokens)
# 문장길이의 평균값, 최대값, 표준편차를 계산해 본다. 
print('문장길이 평균 : ', np.mean(num_tokens))
print('문장길이 최대 : ', np.max(num_tokens))
print('문장길이 표준편차 : ', np.std(num_tokens))

# 예를들어, 최대 길이를 (평균 + 2*표준편차)로 한다면,  
max_tokens = np.mean(num_tokens) + 2 * np.std(num_tokens)
maxlen = int(max_tokens)
print('pad_sequences maxlen : ', maxlen)
print('전체 문장의 {}%가 maxlen 설정값 이내에 포함됩니다. '.format(np.sum(num_tokens < max_tokens) / len(num_tokens)))

문장길이 평균 :  35.76532410522606
문장길이 최대 :  250
문장길이 표준편차 :  34.5032704473211
pad_sequences maxlen :  104
전체 문장의 0.9479316863725208%가 maxlen 설정값 이내에 포함됩니다. 


---
# 모델
---

In [19]:
class BERTDataset(Dataset): 
  def __init__(self, dataset, bert_tokenizer, max_len):
    
    self.sentences = [bert_tokenizer(i, truncation=True, return_token_type_ids=True, padding="max_length",
                                     max_length = max_len, return_tensors = 'pt') for i in dataset['review']]
    self.max_len = max_len
    self.taste = [np.int64(i) for i in dataset['taste']]
    self.quantity = [np.int64(i) for i in dataset['quantity']]
    self.delivery = [np.int64(i) for i in dataset['delivery']]
  
  def __getitem__(self,i):
    self.input_ids = self.sentences[i]['input_ids']
    self.attention_mask_token = self.sentences[i]['attention_mask']
    self.token_type_ids = self.sentences[i]['token_type_ids']

    return self.input_ids, self.attention_mask_token, self.token_type_ids, self.taste[i], self.quantity[i], self.delivery[i]

  def __len__(self):
    return (len(self.taste))

In [20]:
# Dataset test
a = BERTDataset(train_data,tokenizer, 70)
a[1]

(tensor([[    2,  7140,  2119, 13314,  1045,  2119,  1513,  2359, 10283,     3,
              0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
              0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
              0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
              0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
              0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
              0,     0,     0,     0,     0,     0,     0,     0,     0,     0]]),
 tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]),
 tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0,

In [21]:
# 하이퍼파라미터 세팅
max_len = 104
batch_size = 32
warmup_ratio = 0.1
num_epochs = 2
max_grad_norm = 1
log_interval = 300
learning_rate =  1e-6

In [22]:
data_train = BERTDataset(train_data, tokenizer, max_len)
data_test = BERTDataset(test_data, tokenizer, max_len)

In [23]:
train_dataloader = torch.utils.data.DataLoader(data_train, shuffle=True, batch_size=batch_size, num_workers=3, drop_last=True)
test_dataloader = torch.utils.data.DataLoader(data_test, shuffle=False, batch_size=batch_size, num_workers=3, drop_last=True)

In [24]:
# dataloader test 
for a,b,c,d,e,f in train_dataloader:
  print(a)
  print(b)
  print(c)
  print(d)
  print(e)
  print(f)
  print('='*100)
  print('input_ids: ',a)
  print('attention_mask: ',b.shape)
  print('token_type_ids: ',c.shape)
  print('taste_label: ',d.shape)
  break


tensor([[[    2,  7301,  4794,  ...,     0,     0,     0]],

        [[    2,  9560,  2182,  ...,     0,     0,     0]],

        [[    2,  1637,  5723,  ...,     0,     0,     0]],

        ...,

        [[    2,  1223,  4893,  ...,     0,     0,     0]],

        [[    2,  1521,  1059,  ...,     0,     0,     0]],

        [[    2,  7798, 19521,  ...,     0,     0,     0]]])
tensor([[[1, 1, 1,  ..., 0, 0, 0]],

        [[1, 1, 1,  ..., 0, 0, 0]],

        [[1, 1, 1,  ..., 0, 0, 0]],

        ...,

        [[1, 1, 1,  ..., 0, 0, 0]],

        [[1, 1, 1,  ..., 0, 0, 0]],

        [[1, 1, 1,  ..., 0, 0, 0]]])
tensor([[[0, 0, 0,  ..., 0, 0, 0]],

        [[0, 0, 0,  ..., 0, 0, 0]],

        [[0, 0, 0,  ..., 0, 0, 0]],

        ...,

        [[0, 0, 0,  ..., 0, 0, 0]],

        [[0, 0, 0,  ..., 0, 0, 0]],

        [[0, 0, 0,  ..., 0, 0, 0]]])
tensor([1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1,
        0, 1, 1, 0, 1, 1, 1, 1])
tensor([0, 0, 1, 0, 1, 0, 0, 0, 0, 

In [25]:
wandb.init(project = 'klue_bert_TAPT_before',
                 entity="glad415",
                 config = {
                     "hidden_size" : 768,
                     "max_len" : max_len,
                     "batch_size" : batch_size,
                     "learning_rate" : learning_rate,
                     "epochs" : num_epochs,
                     "optimizer" : 'adamW',
                     "loss" : "BCEloss",
                 })

In [26]:
class BERTClassifier(nn.Module):
    def __init__(self,
                 bert,
                 hidden_size = 768,
                 ################# 클래스 수 조정 ##################
                 num_classes=1,   
                 dr_rate=None,
                 params=None):
        super(BERTClassifier, self).__init__()
        self.bert = bert
        self.dr_rate = dr_rate
                 
        self.taste = nn.Linear(hidden_size , num_classes)
        self.quantity = nn.Linear(hidden_size , num_classes)
        self.delivery = nn.Linear(hidden_size , num_classes)

        self.dropout = nn.Dropout(p=dr_rate)

        self.sigmoid = nn.Sigmoid()
    
    def forward(self, input_ids, attention_mask, token_type_ids):

        out = self.bert(input_ids = input_ids.long(), token_type_ids = token_type_ids.long(), attention_mask = attention_mask.to(device))
        out = self.dropout(out.pooler_output)

        taste_out = self.taste(out)
        quantity_out = self.quantity(out)
        delivery_out = self.delivery(out)   

        return self.sigmoid(taste_out), self.sigmoid(quantity_out), self.sigmoid(delivery_out)
    
    ############################# Frezee #############################
    # def freeze_bert_encoder(self):
    #     for param in self.bert.parameters():
    #         param.requires_grad = False
    
    # def unfreeze_bert_encoder(self):
    #     for param in self.bert.parameters():
    #         param.requires_grad = True
    ##################################################################

In [27]:
#BERT 모델 불러오기
model = BERTClassifier(bertmodel, dr_rate=0.3).to(device)

#optimizer와 schedule 설정
no_decay = ['bias', 'LayerNorm.weight']
optimizer_grouped_parameters = [
    {'params': [p for n, p in model.named_parameters() if not any(nd in n for nd in no_decay)], 'weight_decay': 0.01},
    {'params': [p for n, p in model.named_parameters() if any(nd in n for nd in no_decay)], 'weight_decay': 0.0}
]

optimizer = AdamW(optimizer_grouped_parameters, lr=learning_rate)
loss_fn = nn.BCELoss()

t_total = len(train_dataloader) * num_epochs
warmup_step = int(t_total * warmup_ratio)

scheduler = get_cosine_schedule_with_warmup(optimizer, num_warmup_steps=warmup_step, num_training_steps=t_total)

In [ ]:
for e in range(num_epochs):
    train_acc = 0.0
    total_f1 = 0.0
    for batch_id, (input_ids, attention_mask_token, token_type_ids, taste_label, quantity_label, delivery_label) in enumerate(tqdm_notebook(train_dataloader)):
        
        optimizer.zero_grad()
        
        input_ids = input_ids.long().to(device)
        input_ids = input_ids.squeeze(1)

        token_type_ids = token_type_ids.long().to(device)
        token_type_ids = token_type_ids.squeeze(1)
        
        attention_mask_token= attention_mask_token.squeeze(1)

        taste_label = taste_label.float().to(device)
        taste_label = taste_label.unsqueeze(1)

        quantity_label = quantity_label.float().to(device)
        quantity_label = quantity_label.unsqueeze(1)

        delivery_label = delivery_label.float().to(device)
        delivery_label = delivery_label.unsqueeze(1)

        taste_out, quantity_out, delivery_out = model(input_ids, attention_mask_token, token_type_ids)

        # Loss
        ################################################################################################
        taste_loss = loss_fn(taste_out, taste_label)
        quantity_loss = loss_fn(quantity_out, quantity_label)
        delivery_loss = loss_fn(delivery_out, delivery_label)

        total_loss = (taste_loss + quantity_loss + delivery_loss)
        total_loss.backward() 
        ################################################################################################

        torch.nn.utils.clip_grad_norm_(model.parameters(), max_grad_norm)

        optimizer.step()
        scheduler.step()  # Update learning rate schedule

        # Accuracy
        ################################################################################################
        taste_preds = (taste_out >= 0.5).float()
        quantity_preds = (quantity_out >= 0.5).float()
        delivery_preds = (delivery_out >= 0.5).float()

        taste_accuracy = (taste_preds == taste_label).cpu().numpy().mean()
        quantity_accuracy = (quantity_preds == quantity_label).cpu().numpy().mean()
        delivery_accuracy = (delivery_preds == delivery_label).cpu().numpy().mean()

        train_acc += (taste_accuracy + quantity_accuracy + delivery_accuracy) / 3
        ################################################################################################

        # F1_Score
        ################################################################################################
        taste_f1 = f1_score(taste_preds.cpu().data, taste_label.cpu(), average = 'micro')
        quantity_f1 = f1_score(quantity_preds.cpu().data, quantity_label.cpu(), average = 'micro')
        delivery_f1 = f1_score(delivery_preds.cpu().data, delivery_label.cpu(), average = 'micro')
        
        total_f1 +=  (taste_f1 + quantity_f1 + delivery_f1) / 3
        ################################################################################################

        if batch_id % log_interval == 0:

            print(f"epoch {e+1} batch id {batch_id+1} loss {total_loss.data.cpu().numpy():.3f} train acc {train_acc / (batch_id+1):.3f}")
            print(f'taste_accuracy {taste_accuracy:.3f}  | quantity_accuracy {quantity_accuracy:.3f}  | delivery_accuracy {delivery_accuracy:.3f}')
            print(f'f1_score:{total_f1 / (batch_id+1):.3f}')
            print('#'*80)

            # WandB
            #############################################################################################################################
            wandb.log({'interval_Loss': total_loss.data.cpu().numpy(),
                        'interval_taste_Accuracy' :taste_accuracy, 'interval_quantity_Accuracy' : quantity_accuracy, 'interval_delivery_Accuracy' : delivery_accuracy,
                        'interval_taste_F1' : taste_f1, 'interval_quantity_F1' : quantity_f1, 'interval_delivery_F1' : delivery_f1})
            #############################################################################################################################

    print(f"epoch {e+1} epoch_Train_Accuracy {train_acc / (batch_id+1):.3f}, epoch_F1_score {total_f1 / (batch_id+1):.3f}")
    
    # WandB
    #############################################################################################################################
    wandb.log({'epoch_Train_Accuracy' : train_acc / (batch_id+1), 'epoch_F1_score' : total_f1 / (batch_id+1)})
    #############################################################################################################################

    model.eval()
    test_f1 = 0.0
    test_acc = 0.0
    for batch_id, (input_ids, attention_mask_token, token_type_ids, taste_label, quantity_label, delivery_label) in enumerate(tqdm_notebook(test_dataloader)):
        
        input_ids = input_ids.long().to(device)
        input_ids = input_ids.squeeze(1)

        token_type_ids = token_type_ids.long().to(device)
        token_type_ids = token_type_ids.squeeze(1)
        
        attention_mask_token= attention_mask_token.squeeze(1)

        taste_label = taste_label.float().to(device)
        taste_label = taste_label.unsqueeze(1)

        quantity_label = quantity_label.float().to(device)
        quantity_label = quantity_label.unsqueeze(1)

        delivery_label = delivery_label.float().to(device)
        delivery_label = delivery_label.unsqueeze(1)

        taste_out, quantity_out, delivery_out = model(input_ids, attention_mask_token, token_type_ids)

        # Test_Accuracy
        ################################################################################################    
        taste_preds = (taste_out >= 0.5).float()
        quantity_preds = (quantity_out >= 0.5).float()
        delivery_preds = (delivery_out >= 0.5).float()

        taste_accuracy = (taste_preds == taste_label).cpu().numpy().mean()
        quantity_accuracy = (quantity_preds == quantity_label).cpu().numpy().mean()
        delivery_accuracy = (delivery_preds == delivery_label).cpu().numpy().mean()

        test_acc += (taste_accuracy + quantity_accuracy + delivery_accuracy) / 3
        ################################################################################################ 

        # Test_F1_Score
        ################################################################################################
        taste_f1 = f1_score(taste_preds.cpu().data, taste_label.cpu(), average = 'micro')
        quantity_f1 = f1_score(quantity_preds.cpu().data, quantity_label.cpu(), average = 'micro')
        delivery_f1 = f1_score(delivery_preds.cpu().data, delivery_label.cpu(), average = 'micro')
        
        test_f1 +=  (taste_f1 + quantity_f1 + delivery_f1) / 3
        ################################################################################################

    print('-'*40,'Test_Value','-'*40)
    print(f"test_Accuracy {test_acc / (batch_id+1):.3f}, test_F1_score {test_f1/ (batch_id+1):.3f}")
    print('-'*90)
    wandb.log({'Test_acc' : test_acc / (batch_id+1), 'Test_F1_Score' : test_f1/ (batch_id+1)})

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  after removing the cwd from sys.path.


  0%|          | 0/975 [00:00<?, ?it/s]

epoch 1 batch id 1 loss 2.116 train acc 0.458
taste_accuracy 0.375  | quantity_accuracy 0.562  | delivery_accuracy 0.438
f1_score:0.458
################################################################################


In [ ]:
# model.eval()
# test_f1 = 0.0
# test_acc = 0.0
# for batch_id, (input_ids, attention_mask_token, token_type_ids, taste_label, quantity_label, delivery_label) in enumerate(tqdm_notebook(test_dataloader)):
    
#     input_ids = input_ids.long().to(device)
#     input_ids = input_ids.squeeze(1)

#     token_type_ids = token_type_ids.long().to(device)
#     token_type_ids = token_type_ids.squeeze(1)
    
#     attention_mask_token= attention_mask_token.squeeze(1)

#     taste_label = taste_label.float().to(device)
#     taste_label = taste_label.unsqueeze(1)

#     quantity_label = quantity_label.float().to(device)
#     quantity_label = quantity_label.unsqueeze(1)

#     delivery_label = delivery_label.float().to(device)
#     delivery_label = delivery_label.unsqueeze(1)

#     taste_out, quantity_out, delivery_out = model(input_ids, attention_mask_token, token_type_ids)

#     # Accuracy
#     ################################################################################################    
#     taste_preds = torch.argmax(taste_out, dim=1).flatten()
#     quantity_preds = torch.argmax(quantity_out, dim=1).flatten()
#     delivery_preds = torch.argmax(delivery_out, dim=1).flatten()

#     taste_accuracy = (taste_preds == taste_label).cpu().numpy().mean()
#     quantity_accuracy = (quantity_preds == quantity_label).cpu().numpy().mean()
#     delivery_accuracy = (delivery_preds == delivery_label).cpu().numpy().mean()

#     test_acc += (taste_accuracy + quantity_accuracy + delivery_accuracy) / 3
#     ################################################################################################ 

#     # F1_Score
#     ################################################################################################
#     taste_f1 = f1_score(taste_preds.cpu().data, taste_label.cpu(), average = 'micro')
#     quantity_f1 = f1_score(quantity_preds.cpu().data, quantity_label.cpu(), average = 'micro')
#     delivery_f1 = f1_score(delivery_preds.cpu().data, delivery_label.cpu(), average = 'micro')
    
#     test_f1 +=  (taste_f1 + quantity_f1 + delivery_f1) / 3
#     ################################################################################################

# print(f"train acc {test_acc / (batch_id+1):.3f}, f1_score {test_f1/ (batch_id+1):.3f}")
# # wandb.log({'Test_acc' : test_acc / (batch_id+1), 'Test_F1_Score' : test_f1/ (batch_id+1)})

In [ ]:
wandb.finish()

In [ ]:
torch.save(model, '/content/drive/MyDrive/aiffel/AIFFELTON/model_save/koBERT_Multi_label_0907.pt')

In [ ]:
# model = torch.load('/content/drive/MyDrive/aiffel/AIFFELTON/model_save/koBERT_Multi_label_0825_first.pt')

In [ ]:
def predict(predict_sentence):

    dataset_another = pd.DataFrame({'review': predict_sentence, 'taste' : 0 , 'quantity' : 0, 'delivery' : 0}, index = [0])

    another_test = BERTDataset(dataset_another,tokenizer, max_len)
    test_dataloader = torch.utils.data.DataLoader(another_test, batch_size=1, num_workers=5)
    
    model.eval()

    for batch_id, (input_ids, attention_mask_token, token_type_ids, taste_label, quantity_label, delivery_label) in enumerate(test_dataloader):
            
        input_ids = input_ids.long().to(device)
        input_ids = input_ids.squeeze(1)

        token_type_ids = token_type_ids.long().to(device)
        token_type_ids = token_type_ids.squeeze(1)
        
        attention_mask_token= attention_mask_token.squeeze(1)

        taste_label = taste_label.long().to(device)
        quantity_label = quantity_label.long().to(device)
        delivery_label = delivery_label.long().to(device)

        taste_out, quantity_out, delivery_out = model(input_ids, attention_mask_token, token_type_ids)

        for taste, quantity, delivery in zip(taste_out, quantity_out, delivery_out):

            logits_taste = taste.detach().cpu().numpy()
            logits_quantity = quantity.detach().cpu().numpy()
            logits_delivery = delivery.detach().cpu().numpy()

            print('맛에 대한 점수:',logits_taste)
            print('양 or 서비스에 대한 점수:',logits_quantity)
            print('배달에 대한 점수:',logits_delivery)

---
# 결과값 테스트
---

In [ ]:
import warnings
warnings.filterwarnings('ignore')

In [ ]:
predict('맛이 없다')

In [ ]:
predict('서비스가 좋아서 다시 가고 싶어요')

In [ ]:
predict('돈가스 맛집이라해서 가봤는데 양이 너무 적어요')

In [ ]:
predict('음식은 겉바속촉 매장은 깔끔')

In [ ]:
predict('가까워서 빠른 배달이 좋아요 상하이 맛있구요')

In [ ]:
predict('콜라가 거의 다 넘쳤어요 조금 흐른 정도가 아니라 쏟아진 수준이라 감튀도 축축해지고 ㅜㅜ')

In [ ]:
predict('맛 양 배달 모두 만족합니다')

In [ ]:
predict('기사님 너무 친절하시고 감자도 꾹꾹 담아서 가득 주셔서 배부르게 먹었어요 콜라도 뚜껑 이중으로 해주셔서 하나도 안 새고 왔습니당')

In [ ]:
predict('생각보다 빨리 와서 좋았어요 ㅎㅎ')

In [ ]:
predict('다 좋은데 피자가 찌그러져서 왔네요')

In [ ]:
predict('사업 번창하세요')

In [ ]:
predict('다른집 들렸다 온것 같아요')